### ISSUE TITLE
When I execute autoreconf -vfi, got some errors:

### ISSUE THREAD

**Issue by FallacyWalker** [rudimeier/twsapi#9]
![screen shot 2017-04-10 at 15 49 10](https://cloud.githubusercontent.com/assets/20806018/24853209/e4cf0448-1e0c-11e7-99d2-d54b8f0bc39b.png)

OS: Ubuntu 16.04 LTS

**Comment by rudimeier** [comment]
Sorry for not replying.

I assume that you've had a permissions problem. User `walker` need to have write permissions in `/home/twsapifolder/twsapi`. I'm closing this issue, please feel free to reopen if you still have problems.
